/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieapp.view;

import movieapp.entity.FilmTransaction;
import movieapp.entity.SnackTransaction;
import movieapp.util.AppUtil;

/**
 *
 * @author Putu Widyantara
 */
public class DetailPencatatan extends javax.swing.JFrame {
    private String idTransaction;
    private FilmTransaction[] listFilm;
    private SnackTransaction[] listSnack;
    
    /**
     * Creates new form DetailPencatatan
     */
    public DetailPencatatan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 80, 50));

        jLabel3.setForeground(new java.awt.Color(197, 163, 99));
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));

        jLabel5.setForeground(new java.awt.Color(197, 163, 99));
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel7.setForeground(new java.awt.Color(197, 163, 99));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 100, 20));

        jLabel9.setForeground(new java.awt.Color(197, 163, 99));
        jLabel9.setText("jLabel9");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, 130, 270));

        jLabel11.setForeground(new java.awt.Color(197, 163, 99));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("jLabel11");
        jLabel11.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 160, 110, 280));

        jLabel13.setForeground(new java.awt.Color(197, 163, 99));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("jLabel13");
        jLabel13.setToolTipText("");
        jLabel13.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 160, 70, 280));

        jLabel15.setForeground(new java.awt.Color(197, 163, 99));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("jLabel15");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 160, -1));

        jLabel16.setForeground(new java.awt.Color(197, 163, 99));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("jLabel16");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 150, -1));

        jLabel19.setForeground(new java.awt.Color(197, 163, 99));
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/detailpencatatan.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Pencatatan pc = new Pencatatan();
        pc.view();
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    public void view(String idTransaction){
        this.idTransaction = idTransaction;
        this.listFilm = AppUtil.getTransactionRepository().getAllFilmByTransaction(this.idTransaction);
        this.listSnack = AppUtil.getTransactionRepository().getAllSnackByTransaction(this.idTransaction);
        
        jLabel3.setText(AppUtil.getTransactionRepository().getFilmNameById(listFilm[0].getIdFilm()));
        jLabel7.setText(listFilm[0].getStudioTime());
        
        jLabel13.setText("<html>"+AppUtil.getTransactionRepository().getStudioNameByIdFilm(listFilm[0].getIdFilm())+"</html>");
        jLabel19.setText(listFilm[0].getPrice().toString());
        jLabel5.setText(listFilm[0].getCount().toString());
        jLabel11.setText("<html>"+listFilm[0].getSeat()+"</html>");
        jLabel15.setText(listFilm[0].getTotal().toString());
        
        // counting the total snack
        //Integer countSnack = 0;
        Integer totalPriceSnack = 0;
        String tempLabel = "";
        for (SnackTransaction st : listSnack){
            //countSnack =+ st.getCount();
            totalPriceSnack += st.getTotal();
            tempLabel = tempLabel + AppUtil.getTransactionRepository().getSnackNameById(st.getIdSnack());
            tempLabel = tempLabel + " " + st.getSize() + " " + st.getCount().toString() + " " + st.getPrice().toString() + "\n";
        }
        //jLabel12.setText(countSnack.toString());
        jLabel16.setText(totalPriceSnack.toString());
        jLabel9.setText("<html>"+ tempLabel +"</html>");
        
        
        
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
