/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieapp.view;

import java.awt.Desktop;
import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import movieapp.entity.Film;
/**
 *
 * @author Putu Widyantara
 */
public class MovieDetail extends javax.swing.JFrame {
    private Film selectedFilm;
    /**
     * Creates new form MovieDetail
     */
    public MovieDetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        TrailerButton = new javax.swing.JButton();
        BuyButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 190, 310));

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.setFocusPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 100, 30));

        TrailerButton.setBorderPainted(false);
        TrailerButton.setContentAreaFilled(false);
        TrailerButton.setFocusPainted(false);
        TrailerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrailerButtonActionPerformed(evt);
            }
        });
        getContentPane().add(TrailerButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 190, 70));

        BuyButton.setBorderPainted(false);
        BuyButton.setContentAreaFilled(false);
        BuyButton.setFocusPainted(false);
        BuyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuyButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BuyButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 190, 70));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(197, 163, 99));
        jLabel3.setText("Nama Film:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 90, 20));

        jLabel7.setForeground(new java.awt.Color(197, 163, 99));
        jLabel7.setText("Desc");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 530, 120));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(197, 163, 99));
        jLabel9.setText("Durasi");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 30, -1));

        jLabel11.setForeground(new java.awt.Color(197, 163, 99));
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 136, -1, 30));

        jLabel12.setForeground(new java.awt.Color(197, 163, 99));
        jLabel12.setText("jLabel12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 180, -1, -1));

        jLabel13.setForeground(new java.awt.Color(197, 163, 99));
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/moviedetail.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        HomePage homePage = new HomePage();
        homePage.view();
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void TrailerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrailerButtonActionPerformed
        Desktop desktop = Desktop.getDesktop();
        String url = selectedFilm.getTrailer();
        try {
            desktop.browse(new URL(url).toURI());
        } catch (IOException | URISyntaxException e) {
        }
    }//GEN-LAST:event_TrailerButtonActionPerformed

    private void BuyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuyButtonActionPerformed
        StudioSelect ss = new StudioSelect();
        ss.view(selectedFilm);
        dispose();
    }//GEN-LAST:event_BuyButtonActionPerformed

    public void view(Film film){
        this.selectedFilm = film;
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + film.getId()+ ".jpg")));
        
        // title
        jLabel3.setText(film.getName());
        jLabel11.setText(film.getGenre());
        jLabel12.setText(film.getRating().toString());
        jLabel13.setText(film.getPrice().toString());
        jLabel9.setText(film.getDuration().toString());
        jLabel7.setText("<html>" + film.getPlot() + "</html>");
        
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton BuyButton;
    private javax.swing.JButton TrailerButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
