/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieapp.view;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import movieapp.entity.Film;
import movieapp.entity.Snack;
import movieapp.util.AppUtil;

/**
 *
 * @author Putu Widyantara
 */
public class SnackSelect extends javax.swing.JFrame {
    private Film film;
    private String time;
    private Integer ticket;
    ArrayList<String> chair;
    
    ArrayList<JButton> buttonList;
    ArrayList<JLabel> titleLabel;
    ArrayList<JLabel> descLabel;
    
    private Snack[] snack;
    
    /**
     * Creates new form SnackSelect
     */
    public SnackSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.setFocusPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 60, 40));

        jButton1.setText("jButton1");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 90, 100));

        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 60, -1));

        jLabel3.setText("text");
        jLabel3.setMaximumSize(new java.awt.Dimension(20, 16));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 110, 50));

        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, -1));

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 90, 50));

        jButton2.setText("jButton2");
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 90, 100));

        jButton3.setText("jButton3");
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 90, 100));

        jButton4.setText("jButton4");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 80, 100));

        jButton5.setText("jButton5");
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, 80, 100));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snack_list.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        OrderConfirmation oc = new OrderConfirmation();
        oc.view(this.film, this.time, this.ticket, this.chair);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    public void view(Film film, String time, Integer ticket, ArrayList<String> chair){
        this.film = film;
        this.time = time;
        this.ticket = ticket;
        this.chair = chair;
        
        
        this.buttonList = new ArrayList<>();
        buttonList.add(jButton1);
        buttonList.add(jButton2);
        buttonList.add(jButton3);
        buttonList.add(jButton4);
        buttonList.add(jButton5);
        
        this.snack = AppUtil.getSnackRepository().getSnack();
        int i = 0;
        for (JButton button : buttonList){
            button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + this.snack[i].getId()+ ".jpg")));
            i++;
        }
        
        this.titleLabel = new ArrayList<>();
        titleLabel.add(jLabel2);
        titleLabel.add(jLabel4);
        i = 0;
        for (JLabel label : titleLabel){
            label.setText(this.snack[i].getName());
            i++;
        }
        
        this.descLabel = new ArrayList<>();
        descLabel.add(jLabel3);
        descLabel.add(jLabel5);
        i = 0;
        for (JLabel label : descLabel){
            label.setText("<html>" + this.snack[i].getDesc() + "</html>");
            i++;
        }
        
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
