/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieapp.view;

import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import movieapp.entity.Film;
import movieapp.entity.Snack;
import movieapp.util.AppUtil;

import movieapp.entity.SnackDetail;

/**
 *
 * @author Putu Widyantara
 */
public class SnackSelect extends javax.swing.JFrame {
    private Film film;
    private String time;
    private Integer ticket;
    private ArrayList<String> chair;
    
    private ArrayList<JButton> buttonList;
    private ArrayList<JLabel> titleLabel;
    private ArrayList<JLabel> descLabel;
    
    private Snack[] snack;
    
    private ArrayList<SnackDetail> snackDetail;
    
    /**
     * Creates new form SnackSelect
     */
    public SnackSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.setFocusPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 90, 30));

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 150, 160));

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 150, 180));

        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, 150, 180));

        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 160, 180));

        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 170, 180));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snackselect.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        OrderConfirmation oc = new OrderConfirmation();
        oc.view(this.film, this.time, this.ticket, this.chair, this.snackDetail);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SnackDetailSelect sds = new SnackDetailSelect();
        sds.view(this.film, this.time, this.ticket, this.chair, this.snackDetail, 0, this.snack[0].getId());
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SnackDetailSelect sds = new SnackDetailSelect();
        sds.view(this.film, this.time, this.ticket, this.chair, this.snackDetail, 0, this.snack[1].getId());
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SnackDetailSelect sds = new SnackDetailSelect();
        sds.view(this.film, this.time, this.ticket, this.chair, this.snackDetail, 0, this.snack[2].getId());
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SnackDetailSelect sds = new SnackDetailSelect();
        sds.view(this.film, this.time, this.ticket, this.chair, this.snackDetail, 0, this.snack[3].getId());
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        SnackDetailSelect sds = new SnackDetailSelect();
        sds.view(this.film, this.time, this.ticket, this.chair, this.snackDetail, 0, this.snack[4].getId());
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void view(Film film, String time, Integer ticket, ArrayList<String> chair, ArrayList<SnackDetail> snackDetail){
        this.film = film;
        this.time = time;
        this.ticket = ticket;
        this.chair = chair;        
        
        this.buttonList = new ArrayList<>();
        buttonList.add(jButton1);
        buttonList.add(jButton2);
        buttonList.add(jButton3);
        buttonList.add(jButton4);
        buttonList.add(jButton5);
        
        this.snack = AppUtil.getSnackRepository().getSnack();
        int i = 0;
        for (JButton button : buttonList){
            button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + this.snack[i].getId()+ ".jpg")));
            i++;
        }
        
//        this.titleLabel = new ArrayList<>();
//        titleLabel.add(jLabel2);
//        titleLabel.add(jLabel4);
//        titleLabel.add(jLabel6);
//        titleLabel.add(jLabel7);
//        titleLabel.add(jLabel8);
//        i = 0;
//        for (JLabel label : titleLabel){
//            label.setText(this.snack[i].getName());
//            i++;
//        }
        
//        this.descLabel = new ArrayList<>();
//        descLabel.add(jLabel3);
//        descLabel.add(jLabel5);
//        descLabel.add(jLabel9);
//        descLabel.add(jLabel10);
//        descLabel.add(jLabel11);
//        i = 0;
//        for (JLabel label : descLabel){
//            label.setText("<html>" + this.snack[i].getDesc() + "</html>");
//            i++;
//        }
        
        // snack
        this.snackDetail = snackDetail;
        
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
