/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieapp.view;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import movieapp.entity.Film;
import movieapp.util.AppUtil;

import movieapp.entity.SnackDetail;

/**
 *
 * @author Putu Widyantara
 */
public class SnackDetailSelect extends javax.swing.JFrame {
    private Film film;
    private String time;
    private Integer ticket;
    private ArrayList<String> chair;
    
    private Integer start;
    
    private ArrayList<SnackDetail> snackDetail;
    private String idSnack;
    
    private ArrayList<JButton> buttonSize;
    
    private Integer availSnack;
    private Integer buySnack;
    private String tempSize;
    
    /**
     * Creates new form SnackDetail
     */
    public SnackDetailSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("jLabel3");
        jDialog1.getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 30));

        jButton8.setText("OK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 240, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(197, 163, 99));
        jLabel2.setText("Silakan pilih ukuran terlebih dahulu!");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, -1, -1));
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 140, 160));

        jButton2.setText("SMALL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 100, 40));

        jButton3.setText("MEDIUM");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 120, 40));

        jButton4.setText("LARGE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 160, 120, 40));

        jButton5.setText("-");
        jButton5.setEnabled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 50, 40));

        jButton6.setText("1");
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 280, 110, 40));

        jButton7.setText("+");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, 50, 40));

        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 240, 70));

        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.setFocusPainted(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 110, 40));

        jLabel6.setForeground(new java.awt.Color(197, 163, 99));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 160, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/snackdetailselect.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        if (this.start == 1){
            // back to order confirmation
            OrderConfirmation oc = new OrderConfirmation();
            oc.view(this.film, this.time, this.ticket, this.chair, this.snackDetail);
            dispose();
        }else{
            // back to snack select
            SnackSelect ss = new SnackSelect();
            ss.view(this.film, this.time, this.ticket, this.chair, this.snackDetail);
            dispose();
        }
    }//GEN-LAST:event_backButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // small
        if (jButton2.getBackground() != Color.green){
            tempSize = "S";
            jButton2.setBackground(Color.green);
            availSnack = AppUtil.getSnackDetailRepository().getStockByIdSize(this.idSnack, "S");
            
            jLabel2.setText("Tersedia sebanyak: " + availSnack.toString());
            jButton3.setBackground(null);
            jButton4.setBackground(null);
        }else{
            jLabel2.setText("Silakan pilih ukuran snack terlebih dahulu");
            jButton2.setBackground(null);
            jButton3.setBackground(null);
            jButton4.setBackground(null);
        }
        jButton5.setEnabled(false);
        jButton7.setEnabled(false);
        for (JButton button : buttonSize){
            if (button.getBackground() == Color.green){
                jButton5.setEnabled(true);
                jButton7.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // med
        if (jButton3.getBackground() != Color.green){
            tempSize = "M";
            jButton3.setBackground(Color.green);
            availSnack = AppUtil.getSnackDetailRepository().getStockByIdSize(this.idSnack, "M");
            
            jLabel2.setText("Tersedia sebanyak: " + availSnack.toString());
            jButton2.setBackground(null);
            jButton4.setBackground(null);
        }else{
            jLabel2.setText("Silakan pilih ukuran snack terlebih dahulu");
            jButton2.setBackground(null);
            jButton3.setBackground(null);
            jButton4.setBackground(null);
        }
        jButton5.setEnabled(false);
        jButton7.setEnabled(false);
        for (JButton button : buttonSize){
            if (button.getBackground() == Color.green){
                jButton5.setEnabled(true);
                jButton7.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // large
        if (jButton4.getBackground() != Color.green){
            tempSize = "L";
            jButton4.setBackground(Color.green);
            availSnack = AppUtil.getSnackDetailRepository().getStockByIdSize(this.idSnack, "L");
            
            jLabel2.setText("Tersedia sebanyak: " + availSnack.toString());
            jButton3.setBackground(null);
            jButton2.setBackground(null);
        }else{
            jLabel2.setText("Silakan pilih ukuran snack terlebih dahulu");
            jButton2.setBackground(null);
            jButton3.setBackground(null);
            jButton4.setBackground(null);
        }
        jButton5.setEnabled(false);
        jButton7.setEnabled(false);
        for (JButton button : buttonSize){
            if (button.getBackground() == Color.green){
                jButton5.setEnabled(true);
                jButton7.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (buySnack > 0){
            buySnack--;
        }
        jButton6.setText(buySnack.toString());
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (buySnack < availSnack){
            buySnack++;
        }
        jButton6.setText(buySnack.toString());
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        boolean isNotValid = true;
        for (JButton button : buttonSize){
            if (button.getBackground() == Color.green){
                isNotValid = false;
            }
        }
        if (isNotValid){
            jLabel3.setText("Error! Silakan pilih size terlebih dahulu");
            jDialog1.pack();
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);
        }else if (buySnack > availSnack){
            jLabel3.setText("Error! jumlah snack melebihi batas!");
            jDialog1.pack();
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);
        }else{
            // check if exist or not
            boolean isExist = false;
            for (SnackDetail items : this.snackDetail){
                if (items.getId().equals(this.idSnack) && items.getSize().equals(this.tempSize)){
                    isExist = true;
                }
            }
            if (!isExist){
                // if not exist
                SnackDetail sd = new SnackDetail();
                sd.setId(this.idSnack);
                sd.setPrice(AppUtil.getSnackDetailRepository().getPriceByIdSize(idSnack, tempSize));
                sd.setSize(tempSize);
                sd.setStock(buySnack);
                this.snackDetail.add(sd);
            }else{
                for (SnackDetail items : this.snackDetail){
                    if (items.getId().equals(this.idSnack) && items.getSize().equals(this.tempSize)){
                        items.setStock(buySnack);
                    }
                }
            }
            // back to order confirmation
            OrderConfirmation oc = new OrderConfirmation();
            oc.view(this.film, this.time, this.ticket, this.chair, this.snackDetail);
            dispose();
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton8ActionPerformed

    public void view(Film film, String time, Integer ticket, ArrayList<String> chair, ArrayList<SnackDetail> snackDetail, Integer start, String idSnack){
        // init
        this.film = film;
        this.time = time;
        this.ticket = ticket;
        this.chair = chair;
        this.snackDetail = snackDetail;
        this.start = start;
        this.idSnack = idSnack;
        
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + this.idSnack + ".jpg")));
        
        jButton2.setText("S @" + AppUtil.getSnackDetailRepository().getPriceByIdSize(idSnack, "S"));
        jButton3.setText("M @" + AppUtil.getSnackDetailRepository().getPriceByIdSize(idSnack, "M"));
        jButton4.setText("L @" + AppUtil.getSnackDetailRepository().getPriceByIdSize(idSnack, "L"));

        buttonSize = new ArrayList<>();
        buttonSize.add(jButton2);
        buttonSize.add(jButton3);
        buttonSize.add(jButton4);
        
        jLabel6.setText(AppUtil.getSnackRepository().getNameById(idSnack));
        
        this.buySnack = 1;
        
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
