/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package movieapp.view;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import movieapp.entity.Film;
import movieapp.util.AppUtil;

/**
 *
 * @author Putu Widyantara
 */
public class StudioSelect extends javax.swing.JFrame {
    private Film film;
    private List<JButton> listTime;
    private Integer ticket;
    private Integer availTicket;
    private ArrayList<String> listTimeArray;
    /**
     * Creates new form StudioSelect
     */
    public StudioSelect() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BackButton = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        DecreaseButton = new javax.swing.JButton();
        IncreaseButton = new javax.swing.JButton();
        StudioButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        TicketAvailLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jDialog1.getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 10, 200, 30));

        jButton7.setText("OK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 200, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 190, 310));

        BackButton.setBorderPainted(false);
        BackButton.setContentAreaFilled(false);
        BackButton.setFocusPainted(false);
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 510, 90, 30));

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 140, 50));

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 140, 50));

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 170, 140, 50));

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 140, 50));

        DecreaseButton.setText("-");
        DecreaseButton.setEnabled(false);
        DecreaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DecreaseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(DecreaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 50, 40));

        IncreaseButton.setText("+");
        IncreaseButton.setEnabled(false);
        IncreaseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IncreaseButtonActionPerformed(evt);
            }
        });
        getContentPane().add(IncreaseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, 50, 40));

        StudioButton.setBorderPainted(false);
        StudioButton.setContentAreaFilled(false);
        StudioButton.setFocusPainted(false);
        StudioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudioButtonActionPerformed(evt);
            }
        });
        getContentPane().add(StudioButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 210, 70));

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 160, 40));

        TicketAvailLabel.setForeground(new java.awt.Color(197, 163, 99));
        TicketAvailLabel.setText("Silakan pilih film terlebih dahulu!");
        getContentPane().add(TicketAvailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 200, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/studioselect.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        MovieDetail movieDetail = new MovieDetail();
        movieDetail.view(film);
        dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jButton3.getBackground() != Color.green){
            jButton3.setBackground(Color.green);
            availTicket = AppUtil.getStudioTimeRepository().countAvailable(film.getIdStudio(), jButton3.getText());
            TicketAvailLabel.setText("Tersedia " + availTicket.toString());
            jButton4.setBackground(null);
            jButton5.setBackground(null);
            jButton6.setBackground(null);
        }else{
            TicketAvailLabel.setText("Silakan pilih film terlebih dahulu!");
            jButton3.setBackground(null);
            jButton4.setBackground(null);
            jButton5.setBackground(null);
            jButton6.setBackground(null);
        }
        IncreaseButton.setEnabled(false);
        DecreaseButton.setEnabled(false);
        for (JButton button : listTime){
            if (button.getBackground() == Color.green){
                IncreaseButton.setEnabled(true);
                DecreaseButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jButton4.getBackground() != Color.green){
            jButton4.setBackground(Color.green);
            availTicket = AppUtil.getStudioTimeRepository().countAvailable(film.getIdStudio(), jButton4.getText());
            TicketAvailLabel.setText("Tersedia " + availTicket.toString());

            jButton3.setBackground(null);
            jButton5.setBackground(null);
            jButton6.setBackground(null);
        }else{
            TicketAvailLabel.setText("Silakan pilih film terlebih dahulu!");
            jButton3.setBackground(null);
            jButton4.setBackground(null);
            jButton5.setBackground(null);
            jButton6.setBackground(null);
        }
        IncreaseButton.setEnabled(false);
        DecreaseButton.setEnabled(false);
        for (JButton button : listTime){
            if (button.getBackground() == Color.green){
                IncreaseButton.setEnabled(true);
                DecreaseButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jButton5.getBackground() != Color.green){
            jButton5.setBackground(Color.green);
            availTicket = AppUtil.getStudioTimeRepository().countAvailable(film.getIdStudio(), jButton5.getText());
            TicketAvailLabel.setText("Tersedia " + availTicket.toString());

            jButton3.setBackground(null);
            jButton4.setBackground(null);
            jButton6.setBackground(null);
        }else{
            TicketAvailLabel.setText("Silakan pilih film terlebih dahulu!");
            jButton3.setBackground(null);
            jButton4.setBackground(null);
            jButton5.setBackground(null);
            jButton6.setBackground(null);
        }
        IncreaseButton.setEnabled(false);
        DecreaseButton.setEnabled(false);
        for (JButton button : listTime){
            if (button.getBackground() == Color.green){
                IncreaseButton.setEnabled(true);
                DecreaseButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jButton6.getBackground() != Color.green){
            jButton6.setBackground(Color.green);
            availTicket = AppUtil.getStudioTimeRepository().countAvailable(film.getIdStudio(), jButton6.getText());
            TicketAvailLabel.setText("Tersedia " + availTicket.toString());

            jButton4.setBackground(null);
            jButton5.setBackground(null);
            jButton3.setBackground(null);
        }else{
            TicketAvailLabel.setText("Silakan pilih film terlebih dahulu!");
            jButton3.setBackground(null);
            jButton4.setBackground(null);
            jButton5.setBackground(null);
            jButton6.setBackground(null);
        }
        IncreaseButton.setEnabled(false);
        DecreaseButton.setEnabled(false);
        for (JButton button : listTime){
            if (button.getBackground() == Color.green){
                IncreaseButton.setEnabled(true);
                DecreaseButton.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void DecreaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DecreaseButtonActionPerformed
        if (ticket > 1){
            ticket--;
            jButton2.setText(ticket.toString());
        }
    }//GEN-LAST:event_DecreaseButtonActionPerformed

    private void IncreaseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IncreaseButtonActionPerformed
        if (ticket < availTicket){
            ticket++;
        }
        jButton2.setText(ticket.toString());
    }//GEN-LAST:event_IncreaseButtonActionPerformed

    private void StudioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudioButtonActionPerformed
        boolean isError = true;
        // check if no studio is selected
        for (JButton button : listTime){
            if (button.getBackground() == Color.green){
                isError = false;
            }
        }
        if (isError){
            jLabel2.setText("Error! silakan pilih jadwal!");
            jDialog1.pack();
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);
        }else if(availTicket < ticket){
            jLabel2.setText("Error! jumlah tiket melebihi batas!");
            jDialog1.pack();
            jDialog1.setLocationRelativeTo(null);
            jDialog1.setVisible(true);
        }else{
// no error, next
            String selectedTime = "";
            for (JButton button : listTime){
                if (button.getBackground() == Color.green){
                    selectedTime = button.getText();
                }
            }
            SeatSelect seatSelect = new SeatSelect();
            seatSelect.view(this.film, selectedTime, this.ticket);
            dispose();
        }
    }//GEN-LAST:event_StudioButtonActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_jButton7ActionPerformed

    public void view(Film film){
        availTicket = 0;
        ticket = 1;
        jButton2.setText(ticket.toString());
        listTimeArray = AppUtil.getStudioTimeRepository().getListFilmTime(film.getIdStudio());
        // System.out.println(listTimeArray);
        this.film = film;
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/" + film.getId()+ ".jpg")));
        
        List<JButton> buttonList = new ArrayList<>();
        listTime = buttonList;
        
        buttonList.add(jButton3);
        buttonList.add(jButton4);
        buttonList.add(jButton5);
        buttonList.add(jButton6);
        
        
        SimpleDateFormat formatter = new SimpleDateFormat("HH.mm");  
        Date date = new Date();
        String timeNow = formatter.format(date);
        
        int counter = 0;
        for (JButton button : listTime){
            String compTime = listTimeArray.get(counter);
            button.setText(compTime);
            if (compTime.compareTo(timeNow) < 0){
                button.setEnabled(false);
            }
            counter++;
        }
        setLocationRelativeTo(null);
        setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton DecreaseButton;
    private javax.swing.JButton IncreaseButton;
    private javax.swing.JButton StudioButton;
    private javax.swing.JLabel TicketAvailLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
